name: AdrundaalGods
main: de.G4meM0ment.AdrundaalGods
version: 0.00.005
Author: [G4meM0ment]
depend: [Vault]
softdepend: []
commands:
    ag:
        aliases: [ag]
        description: Main command for adrundaal gods
        usage: /ag [reload]