prayItem: WRITTEN_BOOK
prayItemName: Gebetsbuch
prayMenuTitle: Wähle dein Gebet
usePotionEffects: true
disableMovement: true
removeNegativePotionEffects: true
disableChatAndCommands: true
shrineCooldown: 86400000