name: AdrundaalGods
main: de.G4meM0ment.AdrundaalGods
version: 0.00.001
Author: [G4meM0ment]
depend: [Vault]
softdepend: []
commands:
    ag:
        aliases: [ag]
        description: Main command for adrundaal gods
        usage: /ag [reload]
    shrines:
        aliases: [shrines]
        description: Listet deine gefundenen Schreine auf
        usage: /shrines <player>